spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: #from developers.facebook.com AppID
            client-secret: #from developers.facebook.com AppSecret
